name: Run Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prettier:
    name: Run Prettier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run prettier:check

  typescript:
    name: Run TypeScript check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript types check
        run: npm run ts:check

  astro:
    name: Run Astro check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Astro check
        run: npm run astro:check
